corrigiendo actividad 1

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -18,7 +18,7 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
       
-      # Verificar si el archivo SARIF fue generado
+      # Verificar existencia de snyk.sarif
       - name: Verificar existencia de snyk.sarif
         run: |
           if [ -f snyk.sarif ]; then
@@ -26,10 +26,19 @@ jobs:
           else
             echo "ERROR: El archivo snyk.sarif no se encuentra."
             exit 1
+          fi
         shell: bash
-        
-      - name: Generate HTML report from Snyk
-        run: snyk report --file=snyk.sarif --html > snyk_report.html
+
+      - name: Generar reporte HTML desde Snyk
+        run: |
+          if [ -f snyk.sarif ]; then
+            snyk report --file=snyk.sarif --html > snyk_report.html
+          else
+            echo "ERROR: El archivo snyk.sarif no está disponible para generar el reporte."
+            exit 1
+          fi
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
   
       - name: Upload HTML Report as artifact
         uses: actions/upload-artifact@v4
